default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: password
  host: localhost

development:
  <<: *default
  database: notes-api_development

test:
  <<: *default
  database: notes-api_test

production:
  <<: *default
  database: notes-api_production
  # username: notes-api
  # password: <%= ENV['NOTES-API_DATABASE_PASSWORD'] %>
